### ISSUE TITLE
[srally2] The flash effect is about half the size

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#13]
The camera flash effect doesn't seem to be displayed correctly

video
https://youtu.be/XVeRFZ6tExQ?t=5877

Screenshot
![ss 2022-07-25 193140](https://user-images.githubusercontent.com/109840450/180764181-c10108df-cc23-4c56-97af-a6f4f71fcae9.png)

State save
[srally2_20220725_2.zip](https://github.com/trzy/Supermodel/files/9180569/srally2_20220725_2.zip)

Use Google Translation

**Comment by dukeeeey** [comment]
I'll check this one out.

**Comment by dukeeeey** [comment]
I had a quick look at this. The model has loaded correctly. It's drawing correctly. The issue is the model has the wrong orientation. It should be facing the viewer. It's some sort of issue with the matrices. I think it could be using bill-boarding. Need more time to look into it

![image](https://user-images.githubusercontent.com/11051919/180797082-f873c169-bc22-4762-8e29-18ac9d91d0ff.png)

**Comment by dukeeeey** [comment]
Well I checked for billboarding flags. Billboarding would make the model always face the viewer. But they are never set. In fact I am not sure any model3 game uses them at all. If you look at the screenshot above you can see the matrix number is 1021. I wonder if the issue is the hardware never sends all the matrices for the frame. Could be timing related as the timing in sega rally is fubar because the jtag code at the start is patched out. Maybe all the srally2 bugs are caused by the same thing.
