### ISSUE TITLE
An old ancient mistake

### ISSUE THREAD

**Issue by CCCP1982** [trzy/Supermodel#144]
Supermodel_0.3a-git-dec8503

![312961188-0f85573f-a738-4766-9634-4c094e697d7d](https://github.com/trzy/Supermodel/assets/142115581/1129e4b5-7119-487e-9ca9-1f5266cce463)
![312961199-6d48e488-5cf3-40e5-bb74-bdadccb48f96](https://github.com/trzy/Supermodel/assets/142115581/e83dc292-cad8-4401-aa7d-15ab1b0c89d1)

**Comment by trzy** [comment]
I don't understand? I believe these are the correct ROM set names.

**Comment by CCCP1982** [comment]
> I don't understand? I believe these are the correct ROM set names.

The names in CMD do not match . 

Scud is the name of a rum that is spelled incorrectly by Scudau.

magtruck writes the name mgtrkbad at startup.

All other roms are spelled correctly.

https://github.com/trzy/Supermodel/assets/142115581/67a4997c-db49-428b-aaf3-8998f430ba56

**Comment by jaoxford** [comment]
Ok, but are you having any actual issue?

**Comment by CCCP1982** [comment]
> Ok, but are you having any actual issue?

no

**Comment by trzy** [comment]
I think there is some confusion here. “Scudau” is the ROM name for the Australian version of scud. I believe the MAME team went and renamed it a few years ago. You may have an old scud.zip that is actually now called scudau.zip in the official MAME ROM set. As for magtruckbad, a new ROM for mag truck was dumped that fixes the old bad ROM set that was floating around for years. We discovered that graphical glitches in mag truck were caused by the dump being bad and it was redumped a year or two ago. The old ROM is no longer in MAME but we support it still because it was so common. In Games.xml, we simply patch this ROM and call it “magtruckbad”.Sent from my iPhoneOn Apr 1, 2024, at 8:43 AM, CCCP1982 ***@***.***> wrote:﻿

Ok, but are you having any actual issue?

no

**Comment by CCCP1982** [comment]
> [trzy](https://github.com/trzy)

Thank you for the answer!

Unfortunately, Bart is no longer relevant, since UI 1.0.5 no longer supports and downloads data from Games.xml .

**Comment by trzy** [comment]
Where does it get its data from?

**Comment by CCCP1982** [comment]
> Where does it get its data from?

Wart, who are you talking about?)

**Comment by CCCP1982** [comment]
> Where does it get its data from?

Games.xml not linked to ROMS. )
