### ISSUE TITLE
Multiple mice with Linux

### ISSUE THREAD

**Issue by StormedBubbles** [trzy/Supermodel#16]
Hello,

This is a continuation of the discussion from the Supermodel forum.

It doesn't appear to be possible to use multiple mice in the current version of Supermodel with a Linux system (`lamachin`, `lostwsga`, `oceanhun`).

The three ways to allow multiple mice that come to mind are:

- Alternate "raw" input driver for Linux systems (AdvanceMAME did something similar to this)
- Use the ManyMouse library (maybe AdvanceMAME did this; not sure)
- Create a Libretro port of the emulator so that the Libretro `LIGHTGUN` absolute device type can hook into the emulator's own coordinates. The various Libretro MAME ports do this. This would also give a GUI system to allow various emulator settings to be adjusted.

The recent additions are exciting! I could help with the lightgun hookup in a potential Libretro port, but that would mean the port already exists. Other than that, my friends and I are happy to help with testing anything that anyone comes up with!

**Comment by trzy** [comment]
Official RetroArch is not something I am particularly keen on unfortunately. I’d rather Supermodel remain standalone and independent.

Apparently SDL2 does not support multiple mice so the only alternative is to somehow bolt on a library that does (hopefully cross-platform) or use some lower-level API to add that support (not a good idea). Even so this will be tricky because the multiple mouse code must only handle mouse devices while the rest still get handled by SDL2. It would be a fairly involved change to the guts of the input system. 

If someone would like to work on this, I would be happy to offer guidance.

**Comment by StormedBubbles** [comment]
Thanks for your response! I came across [this](https://github.com/libsdl-org/SDL/issues/5927) on the SDL GitHub repo. Hopefully that can lead to something usable in the future.

**Comment by eadmaster** [comment]
+1 for a libretro port, here it is an old port attempt:

https://github.com/libretro/supermodel

**Comment by nadenislamarre** [comment]
patch done here https://github.com/batocera-linux/batocera.linux/pull/8401
don't hesitate to take it into supermodel.
it is a cheat : i heritate sdl2 to replace only mouse functions via evdev.
(replace ID_INPUT_GUN by ID_INPUT_MOUSE ; batocera uses a specific tag for guns)
