### ISSUE TITLE
Harley Davidson and L A Riders:

### ISSUE THREAD

**Issue by Garagefreek** [trzy/Supermodel#164]
During the intro the riders strangely disappear from their bikes when they zoom out into the distance? I don't know if this is a pcb glitch or a bug in the emulator?

**Comment by trzy** [comment]
Can you please confirm against real PCB footage on YouTube? For future bug reports please confirm first. Sent from my iPhoneOn Jul 18, 2024, at 3:20 PM, Garagefreek ***@***.***> wrote:﻿
During the intro the riders strangely disappear from their bikes when they zoom out into the distance? I don't know if this is a pcb glitch or a bug in the emulator?

**Comment by Garagefreek** [comment]
Unfortunately there is no pcb intro footage of it on YouTube. I spotted it on the emulator from my computer..

**Comment by gm-matthew** [comment]
Just observed this myself, features like the rider's head disappear at a distance:

![image](https://github.com/user-attachments/assets/fe1d5c8f-50c4-49f2-8f27-4ce6870c503a)

Although there is no high quality footage to confirm it, I believe that this would also occur on real hardware. The Model 3 is designed to automatically cull small objects if they are far away enough (in order to speed up rendering), and the rider's head counts as a small object. You'd be less likely to notice on real hardware because it runs at a lower resolution (496x384) than most people use to run Supermodel.

**Comment by Garagefreek** [comment]
So 496x384 is the native resolution for model 3?btw thanks for checking..

**Comment by trzy** [comment]
Until we have further evidence, we can't consider this a bug. It is likely the game performing dynamic LOD.
