### ISSUE TITLE
Extra input lag in Super Model loop

### ISSUE THREAD

**Issue by star69rem** [trzy/Supermodel#185]
In https://github.com/trzy/Supermodel/blob/master/Src/OSD/SDL/Main.cpp , the order of the program loop seems to be:

1) Render/run frames on lines 1031-1034
2) Poll inputs on line 1037
3) Sleep on line 1303

Isn't this adding latency? I would think that the sequence should be:

1) poll inputs
2) render/run frames
3) sleep until next frame

Since inputs are polled after rendering, and then sleep happens after polling, the inputs are always behind, currently. 

I tried a build with Inputs->Poll called before render/run frame, and it doesn't seem to hurt anything.

**Comment by trzy** [comment]
That’s a good observation, this might save a frame of latency. You can make the change and submit a PR and I will look at it and approve if there isn’t anything subtly wrong. I don’t remember why it was done this way (probably before the accurate frame timing code was inserted).Sent from my iPhoneOn Aug 31, 2024, at 2:25 PM, star69rem ***@***.***> wrote:﻿
In https://github.com/trzy/Supermodel/blob/master/Src/OSD/SDL/Main.cpp , rendering frames/running frames happens first, then inputs are polled, and then sleep happens on line 1303. Isn't this adding latency? I would think that the sequence should be 1) poll inputs, 2) render/run frames, then 3) sleep until next frame. Since inputs are polled after rendering, and then sleep happens after pulling, the inputs are always behind, currently.
I tried a build with Inputs->Poll called before render/run frame, and it doesn't seem to hurt anything.

**Comment by gm-matthew** [comment]
Made the change myself, pull request submitted. Thanks @star69rem for the suggestion

**Comment by star69rem** [comment]
Thank you @gm-matthew for saving me from having to do that!
