### ISSUE TITLE
Noticeable "clicking" sound in music

### ISSUE THREAD

**Issue by MDashK** [trzy/Supermodel#22]
Using "**Supermodel_0.3a-git-0eef09b_Win64**" version.

Playing Daytona USA 2 Power Edition (also noticeable on Sega Rally 2) there is a random clicking in the bgm sound, I'm assuming it's related to the MPEG decoding.

Here is a ~1m sample where you can clearly listen to the "clicking" multiple times. This seems to happen randomly and sporadicly, but more noticeable in drum beats.

Advised to use earphones or headphones to be more noticeable.

https://mega.nz/file/Mok2zJoJ#OJEvYkO8Nb9kgO3d4btWktHsqocc-V_yRslEO6aVEH8

UPD: Forgot to mention that this did not happen on previous builds like r862. Same PC. Same setup. Nothing changed.

**Comment by toxieainc** [comment]
Maybe due to this? https://github.com/trzy/Supermodel/commit/94d8a1b22d32ddc46a40f8f72fc9b34e55deb4c9

**Comment by MDashK** [comment]
Checking the code you mentioned reminded me of the SoundVolume and MusicVolume options in the config file.
So I changed my settings from:

SoundVolume = 150
MusicVolume = 200

... To ...

SoundVolume = 75
MusicVolume = 125

... And the clicking is gone.

I initially tried with 50/100 values, the clicking was gone but I found it too low, so I upped them to 100/150 and the clicking came back, despite very rarely. 75/125 seems to be the sweet spot.

**Comment by dukeeeey** [comment]
I actually didn't know you could set the volume higher than 100%. The clicking you hear is because the waveform is being flattened in the peaks. This will happen in most audio software if you do the same especially with only 16 bit audio.

**Comment by trzy** [comment]
I didn't know much about audio programming when I wrote the sound mixing and resampling code. That should be performed by SDL automatically using its own internal functions. The linear interpolation for resampling is probably naive and I'll bet audiophiles could perceive a difference between the 16KHz MPEG audio being played at its native 16KHz, rescaled the "right way" (whatever that is) to 44.1KHz, and rescaled my way to 44.1KHz.

I allow volume to exceed 100% because I find it is sometimes easier to balance that way for Daytona 2 in particular, where I think sounds by default are rather quiet. Not sure how else to do it. In reality, how are the sound systems for these arcades wired up and are there built-in amplifiers? For example, are the MPEG board and SCSP audio lines amplified to different levels before being mixed? If so, then the current approach allows for one to naively amplify a given audio source at the risk of clipping. 

Presumably there are smarter ways to perform software mixing that are dynamic and take into account not just the current sample but previous state to create something that sounds good *perceptually*?

**Comment by MDashK** [comment]
Yeah, I actually also found it weird back then, but the config file gave an example like:

;       SoundVolume = 50
;       MusicVolume = 200

So I went with those 150/200 values back then.
I still find it somewhat weird regarding the 125 value, for instance, because usually, I use earphones when I game, and in Windows, a setting of 30 out of 100 is usually the limit before the volume starts to be disconfortable with my earphones.
But still, setting that value to 125 is still not making the volume of the game that loud, so I have to increase in Windows to 36 or 40.

**Comment by trzy** [comment]
It's been a loooong time since I looked at it but one thing you can do is print out the min/max audio values as a percentage before the audio buffers are mixed to see what's going on. My recollection is that Daytona 2 was really quiet. So my *guess* is that the SCSP digital audio output is really low and this might have been because the hardware itself already has an amplifier on it, so the developers reduced the volume to compensate (which I think technically results in a loss of fidelity?).

Check out DSB.cpp's RunFrame() functions. E.g., CDSB2::RunFrame(). The SCSP audio channels are passed in and then you can see that it resamples, mixes, and applies volume right there. At the beginning of this function you could traverse those arrays and print out the max and then also do that again after mixing to see if it ever hits 255.

**Comment by dukeeeey** [comment]
Maybe you could pass float data to sdl? But really this isn't a problem we should be solving.

**Comment by toxieainc** [comment]
One could use SDL_ConvertAudio from my understanding.
If one wants to get fancy AND doesn't want to include many external files, one could also use https://github.com/libsndfile/libsamplerate/tree/master/src . That's what we use in PinMAME for resampling, and its one of the highest quality resamplers out there.
As for the sound being too low on some games: The same we experience in PinMAME, too. E.g. sound settings for DCS-based pinballs in the arcade were usually around 8-12, but in emulation people crank it up to 28 or so, which would blast the speakers if done on a real machine.

**Comment by toxieainc** [comment]
Independent from that, i'm currently preparing a PR to do all the mixing in float, as all the back and forth in the current mixer (float<->int) should not be even faster nowadays, plus one definetly uses some bits on the way.

**Comment by toxieainc** [comment]
This PR now improves overall precision, but i guess the original issue with the clicks will still be there.
(and there is also not much that can be done about that if its really due to the clamping)
