### ISSUE TITLE
Driver forced anisotropic filtering doesn't work

### ISSUE THREAD

**Issue by MaLDox77** [trzy/Supermodel#80]
Hello,

Nvidia driver forced Aniso used to work in old versions of Supermodel.

Oldest verified version that works is r453. Next version that I've verified doesn't work is r846.

Something was done in the middle that has broken the Anisotropic compatibility. Other Driver options like limiting framerate or activating driver FXAA work, but not Aniso.

Anisotropic filtering lack is obvious in racing games where road lines are blurred a few meters away of the car.

Thank you

**Comment by dukeeeey** [comment]
It's because the rendering is done to off screen render targets. Forced AA only works if drawing to the back buffer directly. This is a driver hack really to improve quality.

The rendering engine implements the same algorithm as the original hardware, so you are going to see slightly blurry lines on the road. I can't change this behavior without really breaking other games.
